dist: trusty
language: node_js
os: linux
node_js:
  - "12.18.1"
cache:
  - node_modules
install:
  - npm install
script:
  - npm run lint:styles
  - npm run lint:js
  - npm run build:scssMaps:debug
  - npm run build:library
